AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TODO

Parameters:
  apiBucket:
    Type: String
    Description: The S3 bucket to use for API storage. This bucket should be dedicated to the API and is used to store
      data such as the list of known ship contacts.
    Default: aaronbruckner-tdd-enterprise-api

Globals:
  Function:
    Timeout: 3

Resources:
  # Gets a list of registered contacts (ship location and call sign)
  contactsGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.contactsGET
      Runtime: nodejs8.10
      Role: !GetAtt contactsRole.Arn
      Events:
        restRequest:
          Type: Api
          Properties:
            Path: /contacts
            Method: get
      Environment:
        Variables:
          API_BUCKET: !Ref apiBucket

  # Update a ship's location/call sign
  contactsPut:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.contactsPUT
      Runtime: nodejs8.10
      Role: !GetAtt contactsRole.Arn
      Events:
        # Registers a ship with its call sign and position
        restRequest:
          Type: Api
          Properties:
            Path: /contacts
            Method: put
      Environment:
        Variables:
          API_BUCKET: !Ref apiBucket

  contactsRole: 
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Principal: 
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies: 
        - PolicyName: !Sub ${AWS::StackName}-contacts
          PolicyDocument: 
            Version: 2012-10-17
            Statement: 
              - Effect: "Allow"
                Action: "*"
                Resource: !Sub "arn:aws:s3:::${apiBucket}"
              - Effect: "Allow"
                Action: "*"
                Resource: !Sub "arn:aws:s3:::${apiBucket}/*"

Outputs:
    ApiUrl:
      Description: "API Gateway endpoint URL."
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
